name: Run Python Code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        
    steps:
    - name: Lint with Pylint
      run: |
        pip install pylint
        pip install setuptools
        pylint all_resources/list_all_resources.py

    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: |
        pip3 install azure
        pip3 install azure-cli-core
        pip3 install setuptools
        python3 ./all_resources/list_resource_groups.py
